### ISSUE TITLE
[bug] Destruction tool can't clear out max range due to power cap

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#123]
Just leaving this as a reminder for you Dire 👍

**Comment by MajorTuvok** [comment]
Maybe reduce the destruction cost a little?

In my opinion it seems counter intitutive to make destruction cost more than exchanger and builder together. I'd expect something that solely destroys blocks to cost less power than something that destroys blocks and builds some (especially since in theory voiding these blocks should give it a bit more energy - the mass has to go somewhere afterall...).

For reference (with the current energy usage of 200RF/Block) : 
-destructing a 16X16X16 Area would cost 819.2kRF. 
-The 500kRF Limit results in cubic Area of 13.57 Blocks (so 14X13X13 is pretty much the biggest one can get to) 

So maybe half the energy cost and double the capacity, so that 2 max operations are possible without recharging it?

**Comment by MichaelHillcox** [comment]
That would be up for @Direwolf20-MC to figure out :P I've made the needed changes in #124 but it's more of a generic fix. It would allow @Direwolf20-MC to have a more dynamic range of `energy max` within each of the current tools. 

As for your argument, I do kind of agree, 200RF per block is a bit much for a destruction process. Maybe have a look at what RFTools Builder does when voiding?

On a side note: The Destruction Tool currently lags out a `Mid -> Pretty good` spec'd pc when having the largest area active & highlighting a block. #125

**Comment by Direwolf20-MC** [comment]
Yea I ran into this in my play through. That’ll teach me to test in creative lol

**Comment by Direwolf20-MC** [comment]
Accepted pull request - thank you :). That was pretty much how I planned to do it as well!
