### ISSUE TITLE
[Bug] Client Side Crash when using a destruction gadget on a dynamic tree

### ISSUE THREAD

**Issue by nefolaC4** [Direwolf20-MC/BuildingGadgets#151]
Issue: Game Crashes after destruction gadget is used on dynamic trees.

Context: I have been using building gadgets on a server. I was using the destruction gadget to clear about 150 blocks, including some dynamic trees. I tethered the anchor and upon making the destruction my game crashed. I also tried just dynamic trees (leaves and wood) and got a crash.

I hypothesize that the crash is due to how building gadgets handles the trees temporarily being entities.

Versions:
Building Gadgets 2.4.6
Dynamic Trees 0.9.1d
forge1.12.2-14.23.5.2770

**Comment by McJty** [comment]
Please add a crashlog

**Comment by Sharkie999** [comment]
Got same issue today here is a crash report for you
https://pastebin.com/XDfgW9hQ
![2019-02-15_00 14 16](https://user-images.githubusercontent.com/32912739/52818044-b2980880-30b6-11e9-9236-54f48d0e4407.png)
[crash-2019-02-14_23.51.54-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/2866831/crash-2019-02-14_23.51.54-client.txt)


Fixed by replacing tree's leaves by stone

**Comment by Phylogeny** [comment]
Thank you for the crash report. That confirms that this potential for crashing was fixed in v2.6.0 by b2a501efd6ac7f62df9f7533148f0d1859931d96
