### ISSUE TITLE
[Bug, 2.4.6] Double Slabs (Stone Brick, Cobblestone) and building gadget

### ISSUE THREAD

**Issue by iarspider** [Direwolf20-MC/BuildingGadgets#167]
Double slabs (made of Stone Brick or Cobblestone) are not properly recognized by the building gadget: it treats them both as double Stone slabs.

**Comment by MichaelHillcox** [comment]
Do you mean if you where to break it you would get the block version of it or that it doesn't copy it? I'm confused on what the bug is in this?

**Comment by iarspider** [comment]
Sorry for the confusion. 

When selecting double slab as a building material, the preview shows Double (smooth) Stone Slabs, even if the original block was Double Cobblestone Slab or Double Stone Brick Slab. Not quite sure what the tool expects in player's inventory, but in creative mode it actually places Double Stone Slabs.

Will post a screenshot later.

**Comment by iarspider** [comment]
Trimmed down screenshot: https://imgur.com/7HX90li

**Comment by iarspider** [comment]
A slightly more clear screenshot: https://imgur.com/RChbEgH

**Comment by MichaelHillcox** [comment]
Oh well, that's interesting. I'll take a look :)

**Comment by MichaelHillcox** [comment]
So, I can confirm that this is something that happens. Most likely because they are all the same black with different variants. Although stone, granite etc are the same block but the selection seems to handle them fine. It may be because there is multiple values on the state `seamless=false,variant=stone`? 

The cause is these two lines 
https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java#L256

The original state `IBlockState state = world.getBlockState(pos);` holds the correct properties but after the highlighted lines it losses the correct variant.

**Comment by MajorTuvok** [comment]
But why does InventoryManipulation think of some Properties as unsafe?

**Comment by MajorTuvok** [comment]
Might this cause #164 too?

**Comment by Direwolf20-MC** [comment]
Yea, the purpose of this code is to 'Whitelist' white blockstates are safe to be copied. 

Slab variants are safe. 
Plant growth is not :) -- this would allow you to select a fully grown wheat plant and paste it into the world using seeds, for example. 

I added the appropriate block states, let me know if you find any others that are missing :). 

https://github.com/Direwolf20-MC/BuildingGadgets/commit/bcdaf148223ac73fba32c9dbd83f79a54016ed43
