### ISSUE TITLE
Visual bug with dank/null

### ISSUE THREAD

**Issue by GammelBro** [Direwolf20-MC/BuildingGadgets#176]
If the dank/null menu is open I'am unable to see the ingredients of the copy/paste tool.
Screenshot: [https://i.imgur.com/FaoHMUc.png](https://i.imgur.com/FaoHMUc.png)
Mod Versions: 

- Dank/Null: 1.12-1.4.43
- Building Gadgets: 2.5.0

**Comment by MichaelHillcox** [comment]
This is intresting :) I'll do some looking around to see whats causing that.

**Comment by MichaelHillcox** [comment]
It would appear that this is more of a DankNull issue as their mod handles the Gui in a custom manor and doesn't take into account the 'RenderTooltipEvent' event and thus it doesn't trigger our UI to display the render. You'd likely find that the issue is also in Thaumumcraft. If not then maybe we could look to register our UI in a different way.

**Comment by Direwolf20-MC** [comment]
I agree its probably in dank/null's side. Sorry!
