### ISSUE TITLE
Destruction gadget crash

### ISSUE THREAD

**Issue by DevTimur** [Direwolf20-MC/BuildingGadgets#193]
If you shift-Rclick destruction device, and remove "0" (a zero) from any field, and then press DONE, you will crash

**Comment by Phylogeny** [comment]
This is both invalid and a duplicate of #192.
1. You have not included a link to the crash report here. (which should always be done when reporting a crash)
2. This does not occur in the latest release (v2.5.0).
3. It seems that you have not read the response given to you in #192, as this is explained there. (and since the title has yet to be changed to something sensible)

**Comment by Phylogeny** [comment]
Duplicate of #192
