### ISSUE TITLE
EnderIO Inventory panel support

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#253]
whilst we're at adding support for AE2 and RF, we might as well support EnderIO Inventory panel 👍

**Comment by MajorTuvok** [comment]
I didn't even that exists XD

**Comment by MichaelHillcox** [comment]
Lmao

**Comment by Nerdpie** [comment]
Trying to think of other inventory networks/aggregators, these came to mind:
- Extra Utils 2's Indexer
- Integrated Terminals' Terminal
- RFTools' Modular/Remote Storage
- Botania's Corporea system (not sure if this would make sense thematically; haven't used the Corporea system myself)

**Comment by hnOsmium0001** [comment]
> * Botania's Corporea system (not sure if this would make sense thematically; haven't used the Corporea system myself)

Technically it would, Corporea works like a wirelesss LP system (which is like ExU2 Indexer).

**Comment by Nerdpie** [comment]
Yeah, it makes sense that it would be technically doable.  My concern was more whether it would be thematically fitting, e.g. 'tech mod vs magic mod'.  That then leads to the thought of a configuration to toggle integration for different mods, e.g. if a pack dev feels that something breaks the immersion.  I also wondered about the practicality of an API so that other mods can add their own integration, rather than Building Gadgets having to add support for 'MySuperStorageMod9000', though that becomes a slippery slope with its own can of worms, and outside the scope of this issue...

**Comment by MajorTuvok** [comment]
We are working on the API and an API isn't a 'slippery slope of worms' - it just needs enough thought, to be good...

**Comment by Phylogeny** [comment]
You're right about it being of no relevance whatsoever to this issue, as support for remote inventories can only be added on BG's end.
