### ISSUE TITLE
Crash when equipping any of the gadgets [E2E]

### ISSUE THREAD

**Issue by iDrewt** [Direwolf20-MC/BuildingGadgets#289]
https://pastebin.com/gxygfSk2

I crash when I equip the building gadget, only fix is to not use it or get rid of the mod. Ironically, I get the same crash with builders wand 

E2E modpack. I wasn't always having issues with it, I successfully used it for an entire schematic copy and paste, as well as tons of building-to-me and plane block placements before this. 

(Builder wand crash looks like this)
`java.lang.ArrayIndexOutOfBoundsException: 45
	at cofh.core.gui.container.InventoryContainerItemWrapper.func_70301_a(InventoryContainerItemWrapper.java:142)
	at net.minecraftforge.items.wrapper.InvWrapper.getStackInSlot(InvWrapper.java:68)
	at portablejim.bbw.containers.handlers.HandlerCapability.countItems(HandlerCapability.java:28)
	at portablejim.bbw.containers.ContainerManager.countItems(ContainerManager.java:55)
	at portablejim.bbw.shims.BasicPlayerShim.countItems(BasicPlayerShim.java:69)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:81)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)`

**Comment by MichaelHillcox** [comment]
Did you have any kind of extended inventories attached? cofh satchel etc?

**Comment by MichaelHillcox** [comment]
Related to #280

**Comment by iDrewt** [comment]
Resonant Satchel with Holding IV, in the satchel I do have a /dank/null with stuff in it, but I am not using those materials to my knowledge.

**Comment by MichaelHillcox** [comment]
That's fine, thanks for confirming. It's an issue with how our mod sees the Resonant Satchel, I think I can fix it pretty easily though 👍

**Comment by MichaelHillcox** [comment]
Can you confirm how you bound the satchal to your building gadget?

**Comment by iDrewt** [comment]
I did not. My satchel does not have any item filters that it automatically picks up or holds. I was not trying to use blocks in the satchel.

After some testing (and many crashes) I think it is the fault of the Satchel. I get the same crash with builder wand, when I look at a surface and it brings up the white boxes it'll crash, even without the material to do the action in my inventory or satchel. 

Building gadget (and wand) both work as expected with the /dank/null and no satchel. Might be a TE ticket not you guys or ExU.

**Comment by MichaelHillcox** [comment]
We've had the author of TE on here and they're saying it's due to some protection they've implement. Just means we've got to make a blacklist for that specific item. Although, I really do not understand how the end it's effecting the gadgets as the gadgets can't use the satchel.

- What gadget are you using
- What blocks are you trying to use with the gadget
- Whats in your backpack
- Do you have bubbles (the inventory thing)

Thanks in advance

**Comment by iDrewt** [comment]
Building Gadget (Crashes when in hand) ... I also got the crash when I picked up the copy/paste gadget and tried to move it into the manager. 

Stone, "Build2Me"

Probably too much... http://puu.sh/DiTso/b8f63a715c.png
At the beginning of the game I was using the Big Backpack for everything instead, never had issues. 

Gluttony charm (DarkUtil) and the ring of magnetism (Botania)

**Comment by MichaelHillcox** [comment]
This one is kinda important "Do you have the satchel in bubbles" also thanks 👍

**Comment by iDrewt** [comment]
Bubbles? Baubles? No, it's in my hotbar most of the time. Even if it isn't in my hotbar it will still crash when I look at a surface.

**Comment by MichaelHillcox** [comment]
Baubles* and okay, I'll see what I can find 😄

**Comment by MaxNeedsSnacks** [comment]
Now this is interesting - One of our users reportedly crashed without even having a gadget in his inventory at all. Here's the thread if you're interested.

https://github.com/NillerMedDild/Enigmatica2Expert/issues/1138#issuecomment-487226565

**Comment by MichaelHillcox** [comment]
As this is happening with other mods that would scan for `IItemHandlers` and neither Us or CoFH can figure out why this is happening I'm going to go ahead and say that this is a non issue on our side. It is clear another mod is interfering with how the `Capability` is being dealt and thus we can not make any steps towards supporting this. Within #293 I have attempted to make the way we scan inventories more finite by supping the max inventory size of the players inventory instead of a static `36` value. I can not ensure this has done anything to resolve this issue but for now I am going to close all issues related to this as they are all the same crash report with the same mod pack. 

Unless someone can find me an exact way to reproduce this issue I will not be able to help resolve this issue on our end. 

Thank you to everyone that has reported this issue.

**Comment by MichaelHillcox** [comment]
Please find attached a link to a possible mod that may have been causing this crash 
https://github.com/Direwolf20-MC/BuildingGadgets/issues/280#issuecomment-490269049
