### ISSUE TITLE
Destruction Gadget Overlay cause big Visual Lags

### ISSUE THREAD

**Issue by Fireztonez** [Direwolf20-MC/BuildingGadgets#310]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version: 14.23.5.2831
* Building Gadgets version: 2.6.8
* How to reproduce the issue: Use the Destruction Gadget with a big overlay for area (by example 16x16x16)

Without the overlay, I have constant 120+ FPS, but, with the overlay question to see what I will destroy, I start lagging with probably about 10-15 FPS... Journey Map still show more than 40, but I know for the fact is a lot less than that... I whant to know if this is possible to look question to optimise the overlay, question to have better performance when using the Destruction Gadget.

Thank's for that amazing mod, this is clearly one of the best mod never made, continue your great job Direwolf!!

Fireztonez

**Comment by MajorTuvok** [comment]
You should only have a noticeable lag of a few fps when using the connected surface mode. Last time I tested, we had a performance of 60fps->47fps when moving a lot when in conected surface mode. Since then we also added caching via gl-call list to improve performance - I do not know of such a sever impact. Besides, even if it would be there, I don't think we can improve it by much as we are already pretty close to as good as we can get.

**Comment by MajorTuvok** [comment]
Note that this was on my old, weaker laptop and my next test will be on my new one resulting in presumably higher performance.

**Comment by MajorTuvok** [comment]
I still fail to reproduce such a severe Lag... the best (/worst) I get on my new laptop is a loss of 4fps when I move around a lot. Sorry, I'm pretty sure that this lag does not come from pure buildinggadgets...
