### ISSUE TITLE
Screen goes white when using Destruction Gadget, and then the game crashes

### ISSUE THREAD

**Issue by aaronhowser1** [Direwolf20-MC/BuildingGadgets#322]
* Forge version: 
14.23.5.2836
* Building Gadgets version
BuildingGadgets-2.6.8

* *If the issue is a crash*; An external link to the crash report
https://pastebin.com/ysT8U0tb
https://pastebin.com/JdQY1rPQ

* How to reproduce the issue
I was just clearing a hill with a Destruction Gadget in creative mode, and the screen went white and then the game crashed. It could possibly be a compatibility problem with Dynamic Trees?

**Comment by MajorTuvok** [comment]
I knew that'd happen at some point on some machine...

This is already fixed in the pending release, as it no longer uses recursion to determine connected coords, so that it does not put strain on the call stack.

**Comment by MajorTuvok** [comment]
I need to correct myself: this is the wrong Gadget... We need to use the surface mode also for the destruction Gadget...

**Comment by MajorTuvok** [comment]
To anyone wondering what this issue is about: ConnectedSurface mode uses recursion to determine the connected coordinates. Even though it always terminates, it may still overflow the call stack for large areas. The new BuildingMode System for Exchanging and Destruction Gadget already use an Iterator, but we apperently never applied this to the DestructionGadget. Swapping out the collection of placement positions by either iterating over a Region or ConnectedSurface will fix this.

**Comment by MichaelHillcox** [comment]
Resolved 👍 and pending release. Keep an eye out on curse forge.
