### ISSUE TITLE
Crash involving picking tin wall slabs from Galacticraft

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/BuildingGadgets#330]
* Forge version : MinecraftForge v14.23.5.2815
* Building Gadgets version:  BuildingGadgets-2.6.8
* *If the issue is a crash*; https://gist.github.com/MuteTiefling/75e41c48f2a7cd9ee523cb321c02eaa4

* How to reproduce the issue

Shift Right Click on a Tin Wall Block from Galacticraft with a Building Gadget. Might make a difference that I'm in space, not in an atmosphere. 

After crashing, the game continuously crashes again upon launching the world.

**Comment by MajorTuvok** [comment]
Does this still occur with 2.7.1?

**Comment by MajorTuvok** [comment]
This looks like it's galacticrafts issue though

**Comment by MajorTuvok** [comment]
In 2.7.1 this should be fixed by [catching any exceptions](https://github.com/Direwolf20-MC/BuildingGadgets/blob/712f602e91f1e15694aeb6b4025e3cee8517d45c/src/main/java/com/direwolf20/buildinggadgets/common/tools/ToolRenders.java#L565) the blocks may throw due to us passing in default values. Galacticraft should however use the BlockState passed in, instead of querying the world!

**Comment by MajorTuvok** [comment]
The game crashes again, because you've got the BuildingGadget in your hand and it attempts to render something which keeps throwing an exception... This crash of course also prevents you from taking the BuildingGadget out of your hand. If you've got experience with that, you could edit the BuildingGadget (or it's selected Block) out of your world save. Otherwise, you'll need to wait for us to catch that exception - soryy :(.

**Comment by MichaelHillcox** [comment]
Spam the number key of any other inventory slot as you try to enter the world. Doing this will change the tool in your hand before the render tries to work. You'll then have to ditch that tool and make a new one. Sorry for the inconvenience. I'm looking into it ASAP

**Comment by MajorTuvok** [comment]
This was fixed by galacticraft a while ago - closing
