### ISSUE TITLE
Randomized patterns

### ISSUE THREAD

**Issue by Hillgrove** [Direwolf20-MC/BuildingGadgets#366]
When building bigger than 9x9 (hehe) a surface is rather boring and bland if made from only one block. To make it look nicer you can add depth but you can also add texture to it.

This is easily done in MCEdit with the e.g.  "/brush sphere 15%stone,15%cobblestone,70%grass" command, but it's not a feature I've seen in any mods. Quark's Trowel does emulate this, but it's not the best tool for big surfaces) and not at all for changing already placed blocks.

Thus I think it would be awesome and a great feature if BGs would include this.

**Comment by MajorTuvok** [comment]
The underlying implementation seems to be simple for me (just make the type Provider return blocks), but how can we have a proper interface for this...
Instead of the TransactionGui which Items with the TemplateKey Cap expose, we could expose a gui to select additional blocks with weights?

**Comment by MichaelHillcox** [comment]
My only issue with this is that'd we'd have no way of knowing what items are available in the render compared to the actual build operation. We'd have to set up a system for the render / client to send the final random options to the server to then handle the removal of the blocks as it would become a common issue that it would try and build blocks you don't have enough off if the math was right on the frontend but the RNG came out with a different amount of blocks on the backend

**Comment by MajorTuvok** [comment]
Actually making the number of blocks taken from everything deterministic is simple: instead of choosing randomly, you choose from a given set with the appropiate filling - it wouldn't quite fit into the context of an IBlockProvider I think though (which should just choose one Block, there's no conecpt of it being reset - we could add that if we wanted too). To the Render, we could technically setup similiar caches to how I'm currently doing it with the Templates, but that be a lot of effort. 

It would be way less effort if we created a Block which compiles these thingd into Templates, which can then be pasted. As well as maybe reading in shap-cards as I suggested a while ago. This would however not be that powerful, as you'd have to run to the Template manager first, in order to switch the structure. (and when you build it multiple Times it would be identical - though that can be solved via a custom Template implementation)

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
