### ISSUE TITLE
Cleanup & simplify the building modes

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#384]
I want to work closely with @MajorTuvok to create a solution that perfectly fits our mod and our future plans whilst removing the completely overly complex system that we currently have in place. 

The new system should be:
- [ ] Simplistic by nature
- [ ] No degree required (that's a joke)
- [ ] Support all our current building modes
  - [ ] without separation for exchanging and building modes.
  - [ ] without modifiers built into the mode. Instead, support to add a suppler that'll apply modifiers (related directly to place-on-top )
- [ ] Support new modes like Fill and Hollow for common structures (Sphere, Cube, etc (basically RFTool Shapes but because RFTools system isn't like ours, we should just support them in our own way))
- [ ] Modes should be part of the API but their implementation shouldn't me. How we use the modes once returned from the API is down to use and the same for other modders.

@MajorTuvok please and anything you think might be valid. We can talk more about this in the Discord instead of adding a million comments. I want this system to be something we're both happy with.

**Comment by MajorTuvok** [comment]
I think we can keep the current PlacementSequences as is (except for ConnectedArea as I did insert a kind of hack there, to make it work for the DestructionGadget - they should be seperated).

If we start unifying first, aka all Gadgets rely on AbstractGadget to build `IBuildView` impls, we could implement an appropiate wrapper `IBuildView` depending on the current needs. Aka instead of directly returning SimpleBuildView, perform the transformations on it...?

**Comment by MajorTuvok** [comment]
Also any suggestions on a better name for IBuildView are welcome... Maybe IBuildSequence or IBuildStructure?

**Comment by MichaelHillcox** [comment]
Definitely. That would be where the simplicity by design comes from :)
