### ISSUE TITLE
Item lost bug using tools at max high

### ISSUE THREAD

**Issue by sjusju** [Direwolf20-MC/BuildingGadgets#436]
Forge version : 14.23.5.2846
Building Gadgets version : 2.7.4 (as I updated, 2.8.0 also applies)
How to reproduce the issue : Try to build blocks at higher than maximum high. (y level 256)

Building things over maximum high seems places effect blocks and consumes items. But as soon as effect ends, blocks placed over maximum high, disappears.
I have tested this for both building gadget and copy paste gadget. Both device will do the same thing, consuming items.

Screenshot below is a demonstration with copy paste gadget. I had 3 stacks of grass block before using gadget.
![2020-02-20_19 48 53](https://user-images.githubusercontent.com/61274107/74926955-1a93d400-541a-11ea-84e0-e77e7dc14f15.png)
    ps. Using tools below bedrocks seems fine.

**Comment by MichaelHillcox** [comment]
Please update to 2.8.0 as this may have already been fixed

**Comment by sjusju** [comment]
> Please update to 2.8.0 as this may have already been fixed

Sorry for being lazy on checking update. But new test on 2.8.0 also have the same problem.

**Comment by MichaelHillcox** [comment]
Thanks for the update I'll take a look :)

**Comment by MajorTuvok** [comment]
There used to be a height check in the effect block, I wonder if it is still there...
Can't check atm though

**Comment by MichaelHillcox** [comment]
The effect block is the last thing. If it's in there then that's the bug as we apply damage and take items before the effect block spawns

**Comment by MajorTuvok** [comment]
Hmm, no that's not there anymore...
However: I believe mc not to set any blockstate above build height, even though it allows entities to be there... (as the term build height already suggests, the issue here is not that it doesn't place the blocks above build height, but rather that it spawns effect blocks and consumes Items when you try) 
So adding a check to the Gadgets, not to allow building above the worlds build height, or below 0 should suffice
