### ISSUE TITLE
Immersive Engineering items incompatible

### ISSUE THREAD

**Issue by CrusaderRabbit** [Direwolf20-MC/BuildingGadgets#443]
Seems that a number of Immersive Engineering items do not copy/paste while others do.

Here is a list:
ImmersiveEngineering:Storage_Slab is the steel slab in IE
Wire Connectors and Relays
Lanterns
Transformers
Conveyor belts
Storage Crates

**Comment by MichaelHillcox** [comment]
Any tileentities will not copy in 1.12, are any of those not tile entties?

**Comment by CrusaderRabbit** [comment]
A lot of the metal slabs from Immersive Engineering don't work IE copper slabs.

**Comment by CrusaderRabbit** [comment]
The slabs are not Tile entities.

**Comment by MichaelHillcox** [comment]
I'll check out slabs then 👍

**Comment by MajorTuvok** [comment]
Looking at [this] (https://github.com/BluSunrize/ImmersiveEngineering/blob/f245cb8f0d5b09aae6860771dc360e7ff9eeefab/src/main/java/blusunrize/immersiveengineering/common/blocks/BlockIESlab.java#L26) base class - I remember, why I thought that all IE blocks of interest are TE's. I remember someone in the past complaining about the slabs not being copiable and they turned out to be TE's.

**Comment by MajorTuvok** [comment]
Parfial Duplicate of #184
