### ISSUE TITLE
Building Gadget build preview does not work with Enderio Clear Glass

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Direwolf20-MC/BuildingGadgets#454]
* Forge version: 14.23.5.2847 (1.12.2)
* Building Gadgets version: 2.8.2
   -Enderio Version: 5.1.55
   -EnderCore version: 1.12.2-0.5.73

This is reproducible with the Enderio Quite Clear Glass, Fused Quartz, Enlightened variants, and Dark Variants. The build preview for these glass variants does not show up when attempting to use the building gadget to build with them. Once the build action is started, the blue boxes where the glass is being built appear, but before that there is no indication of where the glass will be built. This happens in every mode of the building gadget.

* How to reproduce the issue
Using the Building gadget, select Enderio Fused Quartz glass or Quite Clear Glass, of normal, dark, or enlightened variants and any dyed color.
Attempt to build using the material and see that no build preview is present.
Activate the building gadget and see that glass is built with, noticing the blue blocks where it will end up.

**Comment by MichaelHillcox** [comment]
Thanks for the report, sorry for not original responding when I saw this. I'll investigate it as I'm collecting a list of 1.12 bugs I'd like to fix.

**Comment by MichaelHillcox** [comment]
Just tested this, it doesn't trigger any of our try catch statements so my only conclusion is that EnderIo is doing something wacky on the glass which we won't support as it would be a whole new feature of the mod to support other mods wacky renders. If this happens when ender io updates to a newer version then I'll look into this again. Sorry for it being a bit crap...
