### ISSUE TITLE
Exchange gadget can bypass destruction gadget disabling

### ISSUE THREAD

**Issue by LemADEC** [Direwolf20-MC/BuildingGadgets#463]
* Forge version 1.12.2-14.23.5.2847
* Building Gadgets version 2.8.2
* How to reproduce the issue
When Destruction gadget is disabled, you can still use Exchange gadget to get the same effect by simply setting it to place any attached block like torch, lever, ladder, etc.
In a PvE context, this can be exploited to make a cheap/op mining tool.
In a PvP/raiding context, we want to build defense easily (placing blocks like obsidian), but still prevent removing such blocks.
The existing Blacklist configuration seems to only prevent placement, which isn't explicit from the comments.

* Possible solutions
- Add a breaking blacklist to complement the existing placing blacklist?
- Add a maximum hardness to breakable blocks?
- Add an option to disable Exchanging gadget?

**Comment by MichaelHillcox** [comment]
Yeah, this has been an issue for a long while. Pretty sure there is a blacklist in 1.12 but it's for all tools which isn't that ideal. This is resolved in 1.14/5 as we've just disabled the gadget being able to place torches and other such things. It's a pain in the ass to resolve because we have to try and check if it's a valid placement before performing the action but there is already things in our way to do that check :cry: we will find a way around it but it's not ideal. I can take another look into the system to see if I can resolve this.

**Comment by LemADEC** [comment]
I had similar problem with my force field upgrades, allowing to break defenses.
The hardness threshold was good fix for that: anything above obsidian hardness can't be broken.

**Comment by MichaelHillcox** [comment]
As of https://github.com/Direwolf20-MC/BuildingGadgets/releases/tag/2.8.3-1.12.2 this should be resolved. Let me know if this is still an issue.
