### ISSUE TITLE
Destruction gadget Fuzzy mode

### ISSUE THREAD

**Issue by meiskam** [Direwolf20-MC/BuildingGadgets#491]
I'd like the ability to use the destruction gadget where it only destroys the type of block you're looking at.  The other gadgets have fuzzy mode, why not this one too?

Use case: world gen put this structure above ground level (it's normally an underground dungeon) and I'd like to get rid of it, it'd would be easier if I could crank up the size and only get rid of the few block types it's made of, without destroying the surrounding terrain. https://i.imgur.com/lgEHVsP.png

**Comment by MajorTuvok** [comment]
The Problem with this, is that you're getting were close to a High-Speed Mining-Tool. Just face clear-stone and you can essentially clrear out the area around all ores...

**Comment by meiskam** [comment]
What can I change to let this idea get approved?

Config option where it's default disabled?  Blacklist stone?

**Comment by meiskam** [comment]
```cfg
"destruction gadget" {
# If enabled, the Destruction Gadget can be taken out of fuzzy mode, allowing only instances of the block clicked to be removed (at a higher cost)
B:"Non-Fuzzy Mode Enabled"=false
```

Errr, looks like the answer is default disabled .. and it's already a feature.

**Comment by MichaelHillcox** [comment]
1.15 and maybe 1.14 don't actually support this feature, I'm not 100% on which ones. I removed it due to one: it being a mining tool and two it being a stupidly intensive task for servers and middle range pc's to handle as could be checking up to 16x16x16 blocks to just find 3 not connected. It's a painful amount of computation to happen on each frame.
