### ISSUE TITLE
Having a small list of pre-build builds for starters

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#493]
For people new to the copy paste gadget it might be nice to have a small list built into the mod of templates for them to paste down, find the right materials etc, a basic onboarding experience for new mod players.

### Implementation
A book icon in the Copy Paste gadget that would open up a Gui with a small list with some images and descriptions of the builds that can be clicked to load right into the gadget to be pasted. This would likely work really well with a pin able material list #444 

Suggested here:
https://www.reddit.com/r/9x9/comments/hr8msj/meta_what_could_building_gadgets_improve_in_the/fy2nlp7?utm_source=share&utm_medium=web2x

**Comment by MajorTuvok** [comment]
@MichaelHillcox this actually correlates kind of with me thinking about importing the structures mc uses for generation into bg and supplying them to users...
Parsing an mc structure file is really simple, because mc already does that so it would only need to be converted to a Template and we could supply these on the remainder of the pages.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
