### ISSUE TITLE
Fabric version

### ISSUE THREAD

**Issue by The-Code-Monkey** [Direwolf20-MC/BuildingGadgets#508]
Hey, would you be ok with me building a version of BuildingGadgets, ChargingGadgets, and MiningGadgets for fabric loader, as i would be happy to do so and support it.

**Comment by MichaelHillcox** [comment]
You'd be better suited contacting us on our discord for this kind of question: https://discord.com/invite/qqUUtu3 as I can talk to you properly about what you'd be infor. I'd also need to talk to @Direwolf20-MC to get his opinion on this. Please do get in touch as it's a complicated subject 👍

**Comment by Direwolf20-MC** [comment]
Hi @The-Code-Monkey 

As the mod is MIT you are allowed to do whatever you want. That said, I fully support you making a fabric version of my mods :). You're most welcome to! 

Per the MIT license, please license your code as MIT as well. The purpose of these mods is to help others learn to make mods, so i want that knowledge to be wide open :).

Finally, I don't feel comfortable designating them as an 'official' port (mostly because I won't be involved in it due to time and knowlege constraints), but please take this response as full permission and appreciation for doing it :). 

Good luck! And feel free to let me know how you make out!!
