### ISSUE TITLE
[Render Glitch] Chisel&Bits Tape Measure

### ISSUE THREAD

**Issue by SirFlip** [Direwolf20-MC/BuildingGadgets#51]
With Building Gadget in Hand:
![2018-08-01_00 08 02](https://user-images.githubusercontent.com/6735323/43490105-8d3d6464-951f-11e8-84be-494f0111ae9e.png)

Normal: 
![2018-08-01_00 07 59](https://user-images.githubusercontent.com/6735323/43490115-9699676a-951f-11e8-9830-6dcbb3c1b1d7.png)

Not sure whether its you or Chisel&Bits

**Comment by Direwolf20-MC** [comment]
I don’t *think* it’s on my end. I heard about this one. I’m almost certain I’m doing it right.

**Comment by AlgorithmX2** [comment]
Since the something changes when your item is in hand its logically something odd about your item.

Reference to second issue: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/412

Specifically,
https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/tools/ToolRenders.java#L152
and
https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/tools/ToolRenders.java#L275

Before Commenting:
![image](https://user-images.githubusercontent.com/2846930/43494807-2e4f9370-94fa-11e8-9681-8bfeecfae1c1.png)

After Commenting both lines:
![image](https://user-images.githubusercontent.com/2846930/43494812-36629d82-94fa-11e8-8ded-24efcc8abb0f.png)

**Comment by Direwolf20-MC** [comment]
See I knew it would take someone smarter than me to figure it out LOL! :)

**Comment by Direwolf20-MC** [comment]
Fixed! Thanks Algo!! https://github.com/Direwolf20-MC/BuildingGadgets/commit/6abbb6362aefd6c15881192527715e0135cdd48e
