### ISSUE TITLE
Weird waterlog issue

### ISSUE THREAD

**Issue by Brandonjaake** [Direwolf20-MC/BuildingGadgets#553]
I have come across a bug with the building gadget and the catwalks from Engineer's Decor. When I tried to build a platform out of said catwalk blocks it spawned water logged variants that flooded the area. 
The same happened with the exchange tool. It how ever did not happen with another mods 'builders wand'.

Im on a 1.16.4 customized Enigmatica 6 Modpack. Let me know if there's anything else i can do to help, cheers.

**Comment by hvdklauw** [comment]
I have an E6 instance, I'll have a look.
As this is also related to the changes around the blacklist.

**Comment by hvdklauw** [comment]
Ok, It's when you copy the raised catwalk that things go wrong.
Here is a dump from the data of the gadget and the original.
The block name is correct, but the state is somehow the waterlogged version, also the variant is 0 where it should be 3.

![java_vWTFdPsLk6](https://user-images.githubusercontent.com/13875/100613958-a590eb80-3315-11eb-8d00-fc03649a882b.png)
![java_nMS5r50n3J](https://user-images.githubusercontent.com/13875/100614090-df61f200-3315-11eb-952e-975c6daef3c8.png)


Maybe the block is set to be waterlogged by default or something, so I think I should add an override list instead of a blacklist where we set things to sane values ourselves?

**Comment by hvdklauw** [comment]
Oh wait, I now see the difference between state and actual state and this might actually be fixed in the development branch.

I'll do some more testing there.

**Comment by hvdklauw** [comment]
Ugh, engineers decor is closed source :S

**Comment by hvdklauw** [comment]
Ok, tested a dev build with this, and this is defenitly a engineers decor issue where their default state is waterlogged.

Now we might NEVER want to place waterlogged items, but I'm not sure.

**Comment by Brandonjaake** [comment]
Yeah cheers for that, wasn't too sure what sort of information you would need

That's extremely odd hahah should I report it to their page then?

**Comment by hvdklauw** [comment]
Already did, to discuss the best solution, might be a bug on their side or something we need to handle. Wait and see.

**Comment by stfwi** [comment]
Hi guys, just a quick confirmation it's a bug in the Decor mod, no action needed here ;) Fix scheduled and handled in the related issue thread. Ty again for reaching out! Cheers, wile

**Comment by MichaelHillcox** [comment]
This issue has been closed by one of our team with an attached reply: 
          
> "Thanks stfwi"

 If you feel this has been done incorrectly then please mention @MichaelHillcox.
