### ISSUE TITLE
Building Gadgets doesn't consistently respect key modifiers for keybinds

### ISSUE THREAD

**Issue by esotericist** [Direwolf20-MC/BuildingGadgets#62]
I've got Mode Switch bound to `R`, and Range bound to `CTRL+R`, but unfortunately hitting `CTRL+R` gets the mode switch UI rather than changing range as expected. Things work correctly if I swap the bindings, though.

This is on the 2.0 alpha.

**Comment by Direwolf20-MC** [comment]
This should be fixed (link below), however please note that if you do what you describe above, you can't use Ctrl+Shift+r to decrease range due to how Minecraft's keybindings work. I tried but was unable to fix that, sorry!

https://github.com/Direwolf20-MC/BuildingGadgets/commit/063ea29fd34aaaf9401bf49fee29fd143f253dde
