### ISSUE TITLE
Lighting glitches when copying slabs as construction paste

### ISSUE THREAD

**Issue by kfish610** [Direwolf20-MC/BuildingGadgets#69]
![2018-08-22_21 20 58](https://user-images.githubusercontent.com/20480949/44504636-9bb9b180-a651-11e8-8f54-23207dd4d21e.png)
Construction paste on left, normal slabs on right.

**Comment by Direwolf20-MC** [comment]
I've tried many different ways to resolve this, and couldn't figure it out. Anyone who has any ideas is more than welcome to chime in heh :)

**Comment by MiningMark48** [comment]
I messed around with this for a bit. The closest thing I could find to making the lighting normal was making Block#getUseNeighborBrightness return true. I thought I would share to see if this would help lead you in the right direction. Images are below for reference.

Without Method (Normal)
![Without Method Img](https://i.imgur.com/iftqTAe.png)

With Method
![With Method Img](https://i.imgur.com/VJUUbSA.png)

**Comment by Phylogeny** [comment]
@MiningMark48 is correct about the root of the problem. The return value of IBlockProperties#useNeighborBrightness is ultimately determined by `Block#useNeighborBrightness`.
I explain more about what 'useNeighborBrightness' does here:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2576750-chisels-bits-flat-colored-blocks?page=28#c551
It may or may not be worth adding a 'useNeighborBrightness' property to your block state, which will yield the result @MiningMark48 posted above. It's up to you, @Direwolf20-MC.

As for why that still doesn't make it look exactly the same in the case of slabs, the reason is due to the difference in ambient occlusion values. `IBlockProperties#getAmbientOcclusionLightValue`'s return value is ultimately determined by `Block#isFullCube` and the block's `Material#blocksMovement`, where as `IBlockProperties#getLightOpacity`'s return value is ultimately determined by `Block#isOpaqueCube`.

You are using the return value of `IBlockProperties#getLightOpacity` to approximate both light opacity and ambient occlusion (which I think is a good idea). This usually works fine, but can lead to inaccuracies in a few cases:
![Construction Block AO Inaccuracies](https://i.postimg.cc/PrcWx0Fz/Construction_Block_AO_Inaccuracies.png)
I really don't think such minor inaccuracies in so few cases warrants giving ambient occlusion its own property; it's almost always results in the exactly correct value, as is.

**Comment by Direwolf20-MC** [comment]
I toyed with overwriting this, but since IBlockProperties#useNeighborBrightness doesn't have access to world/pos I can't figure out the block state i'm mimicing in this method like I do the others. It may not be fixable short of making it always true - which I'm not sure if thats a good idea either :(. It seems to be false way more often than true. Unless I can set that bool randomly in some other method, which i'm hesitant to do.

**Comment by Phylogeny** [comment]
You don't need world/pos. What you're already doing is calling `Block#getLightOpacity` in `ConstructionBlockEntity#setDespawning` to determine how set the `ConstructionBlock#BRIGHT` bool property, and then returning that value in `ConstructionBlock#getLightOpacity` (which has world/pos, but you don't use them) and `ConstructionBlock#getAmbientOcclusionLightValue` (which doesn't have world/pos).

All you need to do is call `Block#getUseNeighborBrightness` in `ConstructionBlockEntity#setDespawning` to determine how to set a new `ConstructionBlock#NEIGHBOR_BRIGHTNESS` bool property, and then return that value in `ConstructionBlock#getUseNeighborBrightness`.

**Comment by Direwolf20-MC** [comment]
Ohh gotcha, I hadn't considered using another blockstate. I see how you did it in your PR and that makes sense :).

**Comment by Direwolf20-MC** [comment]
Thanks @Phylogeny for the pull request, i also added the below commit, which makes them look identical now! WOOT! :)

https://github.com/Direwolf20-MC/BuildingGadgets/commit/b7a9e5a7869ec59886f5e7983998f619152ac224

**Comment by Phylogeny** [comment]
Sweet! :smiley:

**Comment by MiningMark48** [comment]
Awesome :D

**Comment by kfish610** [comment]
Yay

**Comment by MajorTuvok** [comment]
And for the rhyme,
sing and chime, 
Hooray!
