### ISSUE TITLE
building gadget range 12 becomes 13. there is no 12 range (wall)

### ISSUE THREAD

**Issue by jony-test** [Direwolf20-MC/BuildingGadgets#725]
### Building Gadgets version

3.13.0 build 5

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Modpack & Version

0.4.34

### Do you have optifine installed?

No

### Describe the issue

range 12 generates range 13 results

### Steps to reproduce

use building gadget (wall), and select range 12. get a 13 radius wall instead. could be for columns or not, who knows

### Expected behaviour

numbers to actually apply what they mean

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This isn't really a bug, what's happening here is the range is / 2 making it so that we expand the size evenly on the left and right. The range you're modifying isn't the size on the left, top, right. It's the total size of the area. This means a range of 13 can't be even and thus we floor the value back down to the nearest odd number. I've considered reflecting this in the UI but I don't think there is enough requirement for it.
